# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-14 21:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211115_0004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Комментарии к новостям'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='data',
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 11, 15, 0, 12, 8, 514251), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 11, 15, 0, 12, 8, 513251), verbose_name='Опубликована'),
        ),
    ]
