# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-12 21:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20211209_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'менеджер', 'verbose_name_plural': 'менеджеры'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 12, 21, 30, 2, 261937), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 12, 21, 30, 2, 262937), verbose_name='Дата'),
        ),
    ]
