# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-01 09:39
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0021_auto_20220430_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Уведомление')),
                ('date', models.DateTimeField(db_index=True, default=datetime.datetime(2022, 5, 1, 9, 39, 51, 636896), verbose_name='Дата уведомления')),
                ('sdel', models.CharField(max_length=100, verbose_name='название')),
                ('whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 5, 1, 9, 39, 51, 635887), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 5, 1, 9, 39, 51, 636896), verbose_name='Дата'),
        ),
    ]
