# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-01 11:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20220501_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify',
            name='whom',
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 5, 1, 11, 47, 21, 56852), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 5, 1, 11, 47, 21, 56852), verbose_name='Дата'),
        ),
        migrations.DeleteModel(
            name='Notify',
        ),
    ]
