# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-09 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField(verbose_name='начало в')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='окончание в')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Service', verbose_name='услуга')),
            ],
            options={
                'verbose_name': 'расписание',
                'verbose_name_plural': 'расписания',
            },
        ),
    ]
