# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-09 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='discription',
            new_name='description',
        ),
    ]
