# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-01 11:47
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0004_schedule_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='уведомление')),
                ('date', models.DateTimeField(db_index=True, default=datetime.datetime(2022, 5, 1, 11, 47, 21, 60853), verbose_name='дата уведомления')),
                ('sdel', models.CharField(max_length=100, verbose_name='название')),
                ('whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'db_table': 'Notify',
                'ordering': ['-date'],
            },
        ),
    ]
